# Generated by Django 3.1.3 on 2020-11-27 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201126_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='cpu',
            name='socket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.socket'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='socket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.socket'),
        ),
    ]
