# Generated by Django 3.1.3 on 2020-11-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201126_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='cpu_image',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
    ]
