# Generated by Django 3.1.3 on 2020-11-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_cpu_cpu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='cpu_image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
