# Generated by Django 3.1.3 on 2020-12-01 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_cpu'),
        ('product', '0006_auto_20201126_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.product'),
        ),
    ]
