# Generated by Django 3.1.3 on 2020-12-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_build_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='voltage',
            field=models.CharField(default=10, max_length=200),
            preserve_default=False,
        ),
    ]
