# Generated by Django 3.1.3 on 2020-12-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_build_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu_cooler',
            name='cooler_image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='build',
            name='user_token',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
