# Generated by Django 3.1.3 on 2020-12-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20201202_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='motherboard_image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
