# Generated by Django 3.1.3 on 2020-12-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_motherboard_motherboard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='gpu_image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='memory',
            name='memory_image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='power_supply',
            name='power_image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
