# Generated by Django 3.1.3 on 2020-12-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20201203_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu_cooler',
            name='socket',
            field=models.ManyToManyField(blank=True, to='product.Socket'),
        ),
    ]
