# Generated by Django 3.1.3 on 2020-12-04 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_cpu_cooler_socket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='cpu_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='cpu_cooler',
            old_name='cooler_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='gpu_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='memory',
            old_name='memory_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='motherboard_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='power_supply',
            old_name='power_image',
            new_name='image',
        ),
    ]
