# Generated by Django 3.1.3 on 2020-12-04 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20201204_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='cpu',
            new_name='name',
        ),
    ]
