# Generated by Django 3.1.3 on 2020-12-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20201204_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
