# Generated by Django 3.1.3 on 2020-12-08 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_auto_20201204_1617'),
        ('product', '0020_auto_20201208_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.product'),
        ),
    ]
