# Generated by Django 3.1.3 on 2020-12-08 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20201208_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monitor',
        ),
    ]
