# Generated by Django 3.1.3 on 2020-12-08 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_delete_monitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='monitor',
        ),
    ]
