# Generated by Django 3.1.3 on 2020-11-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.CharField(default=200, max_length=200),
            preserve_default=False,
        ),
    ]
