# Generated by Django 3.1.3 on 2020-11-27 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201126_1704'),
        ('service', '0004_auto_20201125_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='monitor',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
        migrations.AddField(
            model_name='purchase',
            name='cpu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.cpu'),
        ),
    ]
