# Generated by Django 3.1.3 on 2020-11-27 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201126_1704'),
        ('service', '0006_purchase_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='quantity',
            new_name='cpu_quantity',
        ),
        migrations.AddField(
            model_name='purchase',
            name='motherboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.motherboard'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='motherboard_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='cpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.cpu'),
        ),
    ]
