# Generated by Django 3.1.3 on 2020-12-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20201208_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='qty',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitems',
            name='sold_price',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
