# Generated by Django 3.1.3 on 2020-12-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20201208_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_sum',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
