# Generated by Django 3.1.3 on 2020-12-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_order_total_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
