# Generated by Django 3.1.3 on 2020-12-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_order_ordered_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='order_token',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
