# Generated by Django 3.1.3 on 2020-12-09 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_orderitems_order_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
