# Generated by Django 3.1.3 on 2020-12-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_auto_20201209_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='sold_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
