# Generated by Django 3.1.3 on 2020-12-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_auto_20201209_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='date_ordered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
