# Generated by Django 3.1.3 on 2020-12-09 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_auto_20201209_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='order_token',
        ),
    ]
