# Generated by Django 3.1.3 on 2020-11-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_remove_product_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='resolution',
        ),
        migrations.AddField(
            model_name='product',
            name='resolution_h',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='resolution_w',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
