# Generated by Django 3.1.3 on 2020-11-26 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20201125_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resolution',
            old_name='resolution',
            new_name='k_def',
        ),
        migrations.RemoveField(
            model_name='product',
            name='resolution_h',
        ),
        migrations.RemoveField(
            model_name='product',
            name='resolution_w',
        ),
        migrations.AddField(
            model_name='product',
            name='resolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.resolution'),
        ),
        migrations.AddField(
            model_name='resolution',
            name='resolution_h',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resolution',
            name='resolution_w',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
