# Generated by Django 3.1.3 on 2020-12-04 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='Cpu',
        ),
    ]
