# Generated by Django 3.1.3 on 2020-12-04 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_auto_20201204_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='name',
        ),
    ]
